apiVersion: apps/v1
kind: Deployment
metadata:
  name: sovereigne2enet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sovereigne2enet
  template:
    metadata:
      labels:
        app: sovereigne2enet
    spec:
      containers:
      - name: sovereigne2enet
        image: agentcygroup/sovereigne2enet:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "prod"
        - name: API_KEY
          value: "dev-key"
---
apiVersion: v1
kind: Service
metadata:
  name: sovereigne2enet-svc
spec:
  type: LoadBalancer
  selector:
    app: sovereigne2enet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
